---
# Handlers pour le rÃ´le samba-ha

- name: restart smb
  service:
    name: smb
    state: restarted

- name: reload smb
  service:
    name: smb
    state: reloaded

- name: restart nmb
  service:
    name: nmb
    state: restarted
